"""empty message

Revision ID: 935b7d73dd8e
Revises: 9950624ba8fb
Create Date: 2020-07-10 02:45:20.112689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '935b7d73dd8e'
down_revision = '9950624ba8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'latitude',
               existing_type=mysql.FLOAT(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
    op.alter_column('positions', 'longitude',
               existing_type=mysql.FLOAT(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
    op.add_column('tracks', sa.Column('roadIds', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'roadIds')
    op.alter_column('positions', 'longitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('positions', 'latitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
