"""empty message

Revision ID: b7c05a84d9a1
Revises: e6dc5cf537b3
Create Date: 2020-07-05 04:44:23.565437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7c05a84d9a1'
down_revision = 'e6dc5cf537b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=True)
    op.drop_table('student')
    # ### end Alembic commands ###
