"""empty message

Revision ID: e6dc5cf537b3
Revises: df5ea54c2561
Create Date: 2020-07-05 04:42:23.337637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6dc5cf537b3'
down_revision = 'df5ea54c2561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=300),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###
