from .models.position import Position
from .models.task import Task
from .models.connection import connection
from datetime import datetime

db = connection.db

def addTask(body):  
    """Create a new Task

    :param body: 
    :type body: dict | bytes
    :param task_id: ID of task
    :type task_id: str

    :rtype: None
    """
    
    # if connexion.request.is_json:
    #     body = Task.from_dict(connexion.request.get_json())  
    task = Task(datetime.now())
    task.add()

    accident = Position(task.id, datetime.now(), 'Destination', '', body['accident_latitude'], body['accident_longitude'], 1)
    departure = Position(task.id, datetime.now(), 'Departure', '', body['departure_latitude'], body['departure_longitude'], 0)
    destination = Position(task.id, datetime.now(), 'Destination', '', body['hospital_latitude'], body['hospital_longitude'], 2)
    p = [accident, departure, destination]
    db.session.add_all(p)
    db.session.commit()

    return {"taskId":task.id}

def findTask(task_id):  
    """Finds task by id

    :param task_id: ID of task that needs to be found. ID was generated By Server.
    :type task_id: str

    :rtype: Task
    """
    task = Task.find(task_id)
    position = Position.find(task_id)  
    print(task)
    print(position)
    return "yes"
